---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wsail.
--- DateTime: 2019/6/26 15:37
---

array = {"Lua","Tutorial"}

for i = 0, 2,1 do
    print(array[i])
end


array1 = {}

for i = 1, 3 do
    array1[i] = {}
    for j = 1, 3 do
        array1[i][j] = i* j
    end
end

for i = 1, 3 do
    for j = 1, 3 do
        print(array1[i][j])
    end

end