---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wsail.
--- DateTime: 2019/6/27 10:41
---

--create()  创建coroutine,返回coroutine，参数是一个函数，当和resume配合使用的时候会唤醒函数调用

co = coroutine.create(
        function(i)
            print(i);
        end
)
coroutine.resume(co,1);
print(coroutine.status(co))


print("---------------------------------")

-- 创建coroutine,返回一个函数，一旦你调用这个函数，就进入coroutine,和create功能重复
co = coroutine.wrap(
    function(i)
        print(i);
    end
)
co(1)

print("---------------------------------")

--status 查看coroutine的状态
--running 返回正在跑的coroutine,一个coroutine就是一个线程
--yield 挂起coroutine,将coroutine设置为挂起状态
co2 = coroutine.create(function()
    for i = 1, 10 do
        print(i)
        if i == 3 then
            print(coroutine.status(co2))
            print(coroutine.running())
        end
        coroutine.yield()
    end
end
)
coroutine.resume(co2)
coroutine.resume(co2)
coroutine.resume(co2)

print(coroutine.status(co2))
print(coroutine.running())
print("---------------------------------")


---生产者消费者问题


local newProductor

function productor()
    local i = 0
    while true do
        i = i + 1
        send(i)    ---将生产的物品发送给消费者
    end
end

function consumer()
    while true do
        local i = receive()
        print(i)
    end
end

function receive()
    local status,value = coroutine.resume(newProductor)
    return value
end

function send(x)
    coroutine.yield(x)
end

newProductor = coroutine.create(productor)
consumer()


