---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wsail.
--- DateTime: 2019/6/27 14:28
---

local function add(a,b)
    assert(type(a) == "number","a 不是一个数字")
    assert(type(b) == "number","b 不是一个数字")
    return a+b
end

add(10)
