---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wsail.
--- DateTime: 2019/6/26 11:39
---

function max(num1,num2)
    if(num1>num2)then
        result = num1;
    else
        result = num2;
    end

    return result;
end

print(max(10,4));

myprint = function(param)
    print("打印函数-   ##",param,"##")
end

function add(num1,num2,functionPrint)
    result = num1+num2
    functionPrint(result)
end

myprint(10)
add(2,5,myprint)

--求最大值和其下标
function maximum(a)
    local mi = 1;
    local m = a[mi];
    for i,val in ipairs(a) do
        if val>m then
            mi = i
            m = val
        end
    end
    return m,mi
end
print(maximum({8,10,23,12,5}))

--求平均值
function average1(...)
    result = 0
    local arg = {...}

    for i,v in ipairs(arg) do
        result = result + v
    end

    print(#arg)
    return result/#arg
end
print(average1(10,5,3,4,5,6))

function average2(...)
    result = 0
    local arg = {...}
    for i,v in ipairs(arg) do
        result = result+v
    end
    print(select("#",...))                --select("#",...)来获取参数的数量

    return result/select("#",...)
end
print(average2(10,5,3,4,5,6))


function fwrite(fmt,...)
    return io.write(string.format(fmt,...))
end

fwrite("runoob\n")
fwrite("%d%d\n",1,2)