---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wsail.
--- DateTime: 2019/6/27 12:16
---


-- r只读，文件必须存在
-- w只写，文件存在，长度清0，不存在则建立该文件
-- a只写附加，文件不存在则建立该文件
-- r+ 读写打开文件，文件必须存在
-- w+ 读写打开文件，文件存在则文件长度清0，不存在则建立该文件
-- a+ 可读可写
-- b 二进制模式，如果文件是二进制文件，可以加上b

--简单模式
-- 以只读方式打开文件
file = io.open("test.lua","r")

-- 设置默认输入文件为test.lua
io.input(file)

-- 输出文件第一行
print(io.read())

-- 关闭打开的文件
io.close(file)

--以附加的方式打开只写文件
file = io.open("test.lua","a")

io.output(file)

io.write("-- test.lua 文件末尾注释")
io.close(file)



-- 完全模式
-- 以只读的方式打开文件
file = io.open("test.lua","r")
-- 输出文件第一行
print(file:read())

file:close()

file = io.open("test.lua","a")
file:write("--test")
file:close()


file = io.open("test.lua","r")

-- 定位到文件倒数第25个位置并使用read方法的*a参数，即从倒数第25个位置读取整个文件
file:seek("end",-25)
print(file:read("*a"))

file:close()


