---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wsail.
--- DateTime: 2019/6/26 16:01
---

-- 泛型迭代器
array = {"baidu","google"}

for i, v in ipairs(array) do
    print(i,v);
end


--无状态迭代器

function square(iteratorMaxCount,currentNumber)
    if currentNumber < iteratorMaxCount then
        currentNumber = currentNumber +1;

        return currentNumber,currentNumber*currentNumber;
    end
end

for i,n in square,3,0
    do
    print(i,n)
end


function iter(a,i)
    i = i + 1;
    local v = a[i]
    if v then
        return i,v
    end
end
function ipairs(a)
    return iter , a,0;
end

--多状态的迭代器

function elementIterator(collection)
    local index = 0
    local count = #collection

    return function()
        index = index + 1
        if index <= count then
            return collection[index]
        end
    end
end

for element in elementIterator(array)
    do
    print(element)
end