---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wsail.
--- DateTime: 2019/6/26 10:45
---

--while循环
a = 10
while(a<20)
    do
    print("a的值",a)
    a = a+1;
end

--for循环
for i = 1,10    -- 定义 i=10 ，从 10 到 1 ，每次 -1;
    do
    print(i)
end


function f(x)
    print("function")
    return x*2;
end

for i = 1,f(5)     -- 第三个参数是可选的 默认为1
    do
    print(i)
end


--泛型for循环          泛型for循环通过一个迭代器来遍历所有值，类似java中的foreach语句
a = {"one","two","three"}
for i,v in ipairs(a)   --其中i是数组索引，v是索引对应的值，ipairs是Lua提供的一个迭代器函数，用来迭代数组
    do
    print(i,v)
end


--repeat...until

n = 10
repeat                     --循环结束后判断
    print("a的值:",n)
    n = n +1
until (n>15)

--循环嵌套
j = 2
for i = 2,10
    do
    for j = 2,(i/j),2
        do
        if(not (i%j))
            then
            break
        end
        if(j>(i/j))
            then
            print("i的值为：",i)
        end
    end
end
