---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wsail.
--- DateTime: 2019/6/26 11:19
---

if (0) then
    print("0为 true")
end

a = 100
if(a<20) then
    print("a小于20")
else
    print("a大于20")
end

print("a的值为：",a)

if (a==10) then
    print("a的值为10")
elseif (a==30) then
    print("a的值为30")
else
    print("没有匹配")
end