---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wsail.
--- DateTime: 2019/6/26 14:44
---

print(string.upper("hello"))  --大小写转换

print(string.lower("Hello"))

print(string.gsub("aaaa","a","z",3))   --字符串替换，aaaa是要替换的字符串，a是要替换的字符，3是替换次数

print(string.find("Hello Lua user","Lua",1)) --字符串搜索，在一个指定的目标字符串中搜索指定的内容（第三个参数为索引），返回其位置，不存在则返回空nil

print(string.reverse("Lua"))-- 字符串反转

print(string.format("the value is:%d",4))

print(string.char(97,98,99,100))  -- 将整形数字转正字符并拼接
print(string.byte("ABCD",4))  -- byte转换字符为整数值
print(string.byte("ABCD"))   --默认为第一个字符

print(string.len("abc"))

print(string.rep("abcd",2))  --返回字符串的n个拷贝

print("hello ".."world") --连接两个字符串

for word in string.gmatch("hello Lua user","%a+") do  --返回一个在字符串str找到下一个符合pattern描述的子串。如果参数pattern描述的字符串没有找到，返回nil
    print(word)
end
print("**")
print(string.match("I have 2 questions for you.","%a+"))