---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wsail.
--- DateTime: 2019/6/27 12:15
---


print(111)-- test.lua 文件末尾注释--test-- test.lua 文件末尾注释--test-- test.lua 文件末尾注释--test-- test.lua 文件末尾注释--test